(* EBNF Grammar for Org documents *)
(* TODO: Can I pass the priorities and keywords as variables? *)
(* TODO: Get tags working. *)

document = (headline)*

(* Headline *)

(* Headline - Top Level *)

headline = header-with-priority-keyword / headline-with-priority / headline-with-keyword / headline-without-keyword-priority-tags

(* Headline - Possible Configurations *)

<header-with-priority-keyword> = headline-identifier <space> headline-priority headline-keyword headline-title <newline*>
<headline-with-priority> = headline-identifier <space> headline-priority headline-title <newline*>
<headline-with-keyword> = headline-identifier <space> headline-keyword headline-title <newline*>
<headline-without-keyword-priority-tags> = headline-identifier <space> headline-title <newline*>

(* Headline - Low Level Elements *)

headline-identifier = #'^\*+'
headline-keyword = ('TODO'|'DONE') <space>
headline-priority = <'[#'> ('A'|'B'|'C') <']'> <space>
headline-title = headline-title-char*
<headline-title-char> = #'[^\n]'

<space> = #' '
<newline> = #'\n'

(* <header-tag-content> = #'[A-Za-z0-9_@#%]+' *)
(* <header-tag-seperator> = ':' *)
(* header-tag = header-tag-content <header-tag-seperator> *)
(* header-tags = &(<space> <header-tag-seperator>) header-tag+ *)
(* header-tags = &' :' header-tag+ *)
